### ISSUE TITLE
Add list of fallback directories to the TCP connect test

### ISSUE THREAD

**Issue by anadahz** [OpenObservatory/ooni-resources#11]
xref: https://trac.torproject.org/projects/tor/ticket/25534

**Comment by hellais** [comment]
We would gladly take a pull request (or a gitdiff via email) that adds the fallback dirs to the csv file list.

This would be a matter of parsing this file: https://gitweb.torproject.org/tor.git/tree/src/or/fallback_dirs.inc and formatting it in the same format as what is inside of: https://github.com/OpenObservatory/ooni-resources/blob/master/bridge_reachability/tor-bridges-ip-port.csv

**Comment by anadahz** [comment]
Closing implemented task.
