### ISSUE TITLE
Update the resources

### ISSUE THREAD

**Issue by anadahz** [OpenObservatory/ooni-resources#12]
@hellais please updated the resources.
I ping @hellais as is the only person with access to update [ooni-resources](https://github.com/OpenObservatory/ooni-resources)

**Comment by hellais** [comment]
They were updated earlier today: https://github.com/OpenObservatory/ooni-resources/commit/b860779764e12ef9bcc6cc47d63385555a2e7173.

**Comment by anadahz** [comment]
Great thanks!
