### ISSUE TITLE
Update resources for desktop and phone probes.

### ISSUE THREAD

**Issue by iapazmino** [OpenObservatory/ooni-resources#13]
A list with sites to observe from Ecuador has been included for the tests[1].
Please, would you update the ooni probes so they take this new resource into account?

[1] https://github.com/citizenlab/test-lists/pull/328

**Comment by R6CG** [comment]
Looks like this happened in [ce5eb053](https://github.com/OpenObservatory/ooni-resources/commit/ce5eb0531f8e3331d5e2f0a6c8e4f98c0337dca5#diff-e908cab16c63adb6db5e171800398193).
