### ISSUE TITLE
Trailing space at the end of tor-bridge CSV lines

### ISSUE THREAD

**Issue by Em4E** [OpenObservatory/ooni-resources#2]
The two files:
 * assets/tor-bridges.tor-bridges-ip-port.csv
 * bridge_reachability/tor-bridges-ip-port.csv

both have a line with an extra space at the end:
```
128.105.214.162,8080,wisctorbridge02,fte 
```
This caused an unexpected result for me because `"fte"` != `"fte "`.

**Comment by hellais** [comment]
Thanks for noticing this. I will fix this and push an update to the resources

**Comment by Em4E** [comment]
Closing because it was fixed by pull request #3 (although that commit was later undone, see #5).
