### ISSUE TITLE
Automatic update undid pull requests #3 and #4

### ISSUE THREAD

**Issue by Em4E** [OpenObservatory/ooni-resources#5]
Commit 194b6703e11621893e8895c2ca5159b37a772525 "Automatic update" undid the changes that were made in pull requests #3 (space in CSV file) and #4 (new obfs4 bridges).

**Comment by hellais** [comment]
Ah I see what happened. In #4 the files in `assets/` were updated instead of the ones in `bridge_reachability/` which are automatically copied to `assets/`.
I will fix it.

Edit: #3 was actually not undone, because the change was made to the source
